### ISSUE TITLE
Tiles creation in PHP or imagic

### ISSUE THREAD

**Issue by ai-tushar** [google/marzipano#89] opened 2017-06-16 04:38 UTC
I am working in a web application. where user can upload 360 images and it can be seen on another page with 360 viewer. now for 360 viewer i want to use marzipano as i think its the best 360 viewer. 
but i am stuck with the tiles creation. from the marzipano tools, when we export a project , the tiles are already created. they are doing in from krpano tools (i still don't know how they do it in server automatically). 
so as per my project requirements, i need to do it in my server as automation process. so i wanted to if marzipano has something which can be used do create the tiles automatically in my server. like with PHP or with imagic.
also if possible let me know how to use krpano tools to create tiles in the server for automation.

Thanks in advance.

**Comment by thriskel** [comment] 2017-06-26 21:24
Check this code, it is python but does the job [https://stackoverflow.com/questions/41856394/script-for-creating-marzipano-scenes](url)

**Comment by etki** [comment] 2017-10-06 17:29
@ai-tushar @thriskel We're faced the same issue, so i've made a [simple library]](https://packagist.org/packages/ama-team/projection-framework). It still sucks (very slow, mapping is not done correctly, no antialiasing - hope this will come in future releases), but does the job with some artifacts.

For everyone else who stumble upon this: having server-side tile creation is good, but the proper way is to create tiles directly in the browser - it's quite rare for server to have GPU on board, while nearly every desktop has one (even if it's buried in CPU), and such processing takes lots of resources (and can bring your website down due to CPU starvation). Marzipano Tool does it that way (in browser) and i found this quite too late, otherwise i'd implement same thing in JS/WebGL.

**Comment by tjgq** [comment] 2017-11-04 04:57
Closing since it's not a bug. You are welcome to continue the discussion in our forum at https://groups.google.com/forum/#!forum/marzipano.

**Closed by tjgq** 2017-11-04 04:57 UTC
