### ISSUE TITLE
Cross-domain video not supported on IE11

### ISSUE THREAD

**Issue by nkmadala** [google/marzipano#115] opened 2017-11-01 14:15 UTC
Hi,
We are streaming a 360 video from a CDN and we are not able to see the video but able to hear the audio on IE11. Our CDN has the CORS enabled. Is there any work around to overcome this issue for IE11 ? Other browsers just play fine. We have mandatory requirement to support IE11. 

Console log shows : SCRIPT5022: SecurityError -  marzipano.js (7,14021)

Can you please help us on this?

**Comment by manuelcabral** [comment] 2017-11-01 15:34
I don't think there is a way to fix this in IE11. The problem is that IE11 [does not support video textures](https://connect.microsoft.com/IE/feedbackdetail/view/941984/webgl-video-upload-to-texture-not-supported). The [workaround](https://github.com/google/marzipano/blob/166bff0c69c60fdbba64ee10c60f98ef2cc7311c/demos/video-multi-res/VideoAsset.js#L19) that we use in the video demo is to paint the video into a canvas and use that as a texture. However this [does not work](https://connect.microsoft.com/IE/feedback/details/967946/support-crossorigin-cors-for-drawing-video-to-canvas-both-2d-and-webgl) for cross-domain videos.

**Comment by nkmadala** [comment] 2017-11-02 11:52
Thank you manuelcabral for the response.

**Comment by tjgq** [comment] 2018-07-11 00:47
Closing since it's impossible to work around.

**Closed by tjgq** 2018-07-11 00:47 UTC
