### ISSUE TITLE
Uncontrollable shaking in WebVR demo

### ISSUE THREAD

**Issue by Mauroamb** [google/marzipano#182] opened 2018-08-04 20:39 UTC
On Display the stereoscopic panorama side-by-side.

http://www.marzipano.net/demos/side-by-side/index.html

He is shaking wildly on mobile devices, I tested on three Moto G4, Moto G5 and Moto G6 machines all with gyroscopes.
But it's shaking in almost every browser tested Chrome, Chrome Canary, Edge. in Firefox nothing happens and the Samsung browser works normally.

Is it any incompatibility with new versions of mobile browsers or some configuration problem?

**Comment by tjgq** [comment] 2018-08-10 21:42
Since the side-by-side demo doesn't have gyroscope support built in, I'm assuming this occurs on a modified version of the demo.

Does the [device-orientation demo](http://www.marzipano.net/demos/device-orientation/index.html) have the same problem on that device?

**Comment by Mauroamb** [comment] 2018-08-11 16:46
Hello,

http://www.marzipano.net/demos/device-orientation/index.html

The above guidance demonstration works normally on the above devices, as I assume that it also uses the gyroscope and the accelerometer to determine the position of the device.

But side by side does not work properly, it is shaking, as the utility of the screen being divided (side by side) is only to see in a cardboard, or vr glasses, it turns out that the resource below is useless, since it is impossible to see something of this way.

http://www.marzipano.net/demos/side-by-side/index.html

Unless you have any updates. The Samsung Internet browser is the only one that still supports this script, but for what time we do not know.

**Comment by cougaro** [comment] 2018-12-11 14:16
Hi all! 

Any news about this bug ? I have the same problem on many devices. The gyroscope works perfectly on "single" view, but when I switch on "VR" mode it starts shaking. 
Please check it out the demo video.

[demo_video.zip](https://github.com/google/marzipano/files/2667900/demo_video.zip)

**Comment by tjgq** [comment] 2019-02-24 23:20
@peppemas Can you provide the source code for a full example? I don't see what would cause the gyroscope controls to work in the single view version, but not in the side-by-side one.

**Comment by peppemas** [comment] 2019-02-25 06:42
@tjgq hi! Just try this:

http://www.marzipano.net/demos/webvr/index.html

On devices like Honor View 10 you can see the problem. Actually I think it's not a gyroscope hardware problem because with the single view example it works and also with my own native opengl app I have no problems. It could be the webVR API.

**Comment by tjgq** [comment] 2019-02-25 22:23
Okay, so the problem is with the webvr demo. (Neither the side-by-side nor the device-orientation demos use WebVR. The side-by-side demo doesn't use the orientation sensor at all, and the device-orientation demo uses the DeviceOrientation API, which is separate from WebVR.)

The WebVR demo doesn't process the sensor orientation in any way - it just [feeds it directly into the view](https://github.com/google/marzipano/blob/master/demos/webvr/index.js#L151). So, at first glance, this problem should also affect every other WebVR app (unless it somehow filters the sensor orientation to make it less noisy). Can you confirm that only the Marzipano WebVR demo is affected?

It's also worth noting that the demo uses an outdated version of the WebVR API (#103). This *may* be fixable by migrating to the latest version of the spec, but I haven't tried since I don't have a VR device to test with.

**Comment by peppemas** [comment] 2019-02-26 08:01
Hi @tjgq

I'm not sure that the problem is completely to be assigned to WebVR API. I just try this: 

With Android Chrome (version 72.0.3626.105):

- I enabled the webVR (chrome://flags#enable-webvr) 
- Launched the 360 Panorama Example on [webvr samples](https://webvr.info/samples/XX-360-panorama.html) and it works. 

The example use a different approach on getting projection matrix check it out there: 

https://github.com/toji/webvr.info/blob/c45c0250baac10ec08749d8ebc15e71501bd76c7/samples/XX-360-panorama.html#L257-L262

**Comment by tjgq** [comment] 2019-03-10 00:05
Thanks for the pointers. I've updated the WebVR demo to work with the latest spec, and tested it on a Google Cardboard.

Please reopen if it still doesn't work with other WebVR displays.

**Closed by tjgq** 2019-03-10 00:05 UTC
Labels: bug, need more info
