### ISSUE TITLE
Performance issue on first load.

### ISSUE THREAD

**Issue by jimblue** [google/marzipano#139] opened 2017-12-27 15:29 UTC
Hello,

First thanks for your amazing library!

I use `Marzipano` on this [website](http://immersion-pictures.com) in the project section and 360 tab.

It's working great but I've notice marzipano is pretty slow on first load while the next created pano are much faster to load.

I'm sure there is some kind of optimisation to do. Could you give me a hint?

Here is how I use `Marzipano`:

```js
import helpers from '../modules/utilities/helpers'
import * as lightbox from '../modules/components/lightbox'
import getAjax from '../modules/utilities/getajax'
import Marzipano from 'marzipano/dist/marzipano'
import DeviceOrientation from '../modules/components/deviceorientation'

// PROJECT LIGHTBOX
// ––––––––––––––––––––––

const projectElements = document.querySelectorAll('.project-card')

// For each videos
for (let i = 0; i < projectElements.length; i++) {
  const thisProject = projectElements[i]
  const thisProjectUrl = thisProject.dataset.project

  // On click
  thisProject.addEventListener('click', () => {
    // Ajax HTML content of the current project
    getAjax(thisProjectUrl, projectHTML => {
      // Create lightbox
      const projectLightbox = lightbox.create(projectHTML, {
        afterShow: () => {
          const projectWrapper = document.querySelector('.project-wrapper')
          const panoID = 'project-panorama-image'
          const panoElement = projectWrapper.querySelector(`#${panoID}`)
          const panoImageUrl = panoElement.dataset.pano

          // Degrees to radians
          const degrees2radians = Math.PI / 180

          // Marzipano options
          const panoOptions = {
            controls: {
              mouseViewMode: 'drag'
            }
          }

          // Create viewer
          const viewer = new Marzipano.Viewer(panoElement, panoOptions)

          // Register the custom control method.
          const deviceOrientationControlMethod = new DeviceOrientation()
          const controls = viewer.controls()
          controls.registerMethod('deviceOrientation', deviceOrientationControlMethod)

          // Create source
          const source = Marzipano.ImageUrlSource.fromString(panoImageUrl)

          // Create geometry
          const geometry = new Marzipano.EquirectGeometry([{ width: 3000 }])

          // Create view
          const viewLimiter = Marzipano.RectilinearView.limit.traditional(1024, 100 * degrees2radians)
          const viewParameters = {
            yaw: 0 * degrees2radians, // pan (degrees)
            pitch: 0 * degrees2radians, // tilt (degrees)
            fov: 120 * degrees2radians // field of view (degrees)
          }
          const view = new Marzipano.RectilinearView(viewParameters, viewLimiter)

          // Create scene
          const scene = viewer.createScene({
            source: source,
            geometry: geometry,
            view: view,
            pinFirstLevel: true
          })

          // Add rotation
          const autorotate = Marzipano.autorotate({
            yawSpeed: 0.03, // Yaw rotation speed
            targetPitch: 0, // Pitch value to converge to
            targetFov: Math.PI / 2 // Fov value to converge to
          })
          viewer.setIdleMovement(500, autorotate) // Start after Xms of inactivity

          // Display scene
          scene.switchTo()

          // Device orientation button
          let enabled = false

          const orientationButton = document.querySelector('#orientation')

          const enableDeviceOrientation = () => {
            deviceOrientationControlMethod.getPitch((err, pitch) => {
              if (!err) view.setPitch(pitch)
            })
            controls.enableMethod('deviceOrientation')
            enabled = true
          }

          const disableDeviceOrientation = () => {
            controls.disableMethod('deviceOrientation')
            enabled = false
          }

          const toggleDeviceOrientation = () => {
            if (enabled) disableDeviceOrientation()
            else enableDeviceOrientation()
          }

          orientationButton.addEventListener('click', toggleDeviceOrientation)
        }
      })

      // Show the lightbox
      projectLightbox.show()
    })
  })
}
```

Thank you 😄 !

**Comment by tjgq** [comment] 2017-12-30 16:23
I tried clicking some of the images in the Featured Projects / 360° VR section, and I can't reproduce what you describe (the first clicked pano doesn't seem to load noticeably slower than the rest).

Your code looks reasonable to me. I would note the following:

- Your panos are a single equirectangular image, so the loading time is the time it takes to download the entire image. If this is an issue, you can make it perceptually faster on slower connections by using a multi-level geometry, where the first level is at a lower resolution and can be shown while the full-resolution version loads.

- You're creating a fresh Viewer instance every time a pano is displayed. Viewer instances hold references to DOM elements, so they might not be garbage collected and take up memory unnecessarily. To prevent this you should call `Viewer#destroy` when the pano is closed.

**Comment by jimblue** [comment] 2017-12-30 16:36
Hey @tjgq !

Thank you so much for your feedback, I'm gonna work on this.

About using multi-level geometry, I've try the output of Marzipano tool that use it and I would love to use it. It's true that performances and loading time are better.

My problem is to use this technique I need to upload the entire folder created by Marzipano tool, but my CMS (Grav) doesn't allow me to do that.

That's why I was asking if you have some plan to make Marzipano tool open source here: #133

**Comment by jimblue** [comment] 2018-03-20 15:15
Hi @tjgq !

I follow your advice to destroy Marzipano viewer instance when the pano is closed.
But I've just discover after some test that it's working.

When I close a pano and open an other one, there is fraction of second while you can see the first pano.

To check this I console.log `viewer` var after destroying it and it seems that the viewer remains...

**Comment by tjgq** [comment] 2018-03-20 17:28
Calling `Viewer#destroy` will not delete the `viewer` variable, but it should remove the viewer from the page.

Is the link you posted above up to date? I can't reproduce the issue you describe.

**Comment by jimblue** [comment] 2018-03-20 19:55
Yes it's up to date, try to open one panorama after an other and you will see previous pano for a fraction of second just before the new one is loaded.

Ok about `viewer#destroy`, I better understand about the `console.log` returning the viewer now.

Actually here is the order of event:

- `lightbox#close`
- `viewer#destroy`
- `lightbox#destroy`

To be sure viewer is destroy I've try to delete not destroy the lightbox. (#69 read it could be a problem if the container is destroy before the viewer.)

In any case the ghost previous pano remain.

**Comment by tjgq** [comment] 2018-03-20 21:57
Sorry, I don't see it.

Each `Viewer` instance has its own `<canvas>` element where the panorama is rendered (you can obtain it by calling `viewer.stage().domElement()`). Since you instantiate a separate `Viewer` for each panorama, the only explanation I can come up with for the bug you describe is that the old `<canvas>` element is still in the DOM when you open a panorama for the second time.

I set some breakpoints in the code, and that doesn't seem to be the case: it looks like the entire `#project-panorama-image` div is removed from the DOM when the first panorama is closed, and a fresh one is inserted when the second one is opened, so there's never more than a single `<canvas>` element 
 on the page. Either there's a race condition that I'm not hitting, or I'm not interacting the page in the same way.

**Comment by jimblue** [comment] 2018-03-21 02:39
That's really strange you can see the problem.
I've just made a [screen capture](https://drive.google.com/file/d/18h00H8z0nrkJAdcPhQZpc7cm04mgBWaa/view). You can play it in slow mo to better see the problem.

I'm using last chrome version `65.0.3325.162 `. I've disable the cache via the console and I've also clear all website cache to be sure.

You can see the lightbox that contain the viewer is properly removed on close.

But the ghost panoramas are still there.

Let me know what would you need to better understand the problem?

Thanks for your help.

Cheers

**Comment by tjgq** [comment] 2018-03-21 03:21
Wild theory: I noticed that the pano URL comes from the `data-pano` attribute on the `#project-panorama-image` element. I don't know how this attribute is set, but I suspect you might be using some kind of MVC framework to render a template into the DOM every time a panorama is clicked.

Could the problem be that, when you click to open the modal, the data attribute still contains the previous value, causing the modal template to be rendered twice? As a test, can you log immediately after instantiating the viewer, and make sure it only occurs once every time you click?

**Comment by jimblue** [comment] 2018-03-21 05:35
Indeed `data-pano` attribute is set server side by my PHP CMS.
I though about what you said but it's impossible as each `data-pano` attribute is a different page url.
(you can navigate to each of them)
The lightbox simply load the page content trough an `ajax` request then add it to the dom inside the lightbox. Once the content of the lightbox is loaded marzipano is instantiated.

To be sure `data-pano` can not still contains the previous value I've also try to reset `viewer` and data-pano` variables after destroying viewer:

```
// Desfine destroy process
      destroyProcess = () => {
        // Destroy current instance of Marzipano viewer
        if (viewer) viewer.destroy()
        panoImageUrl = null
        viewer = null
      }
```

**Comment by tjgq** [comment] 2018-07-11 00:15
As we were unable to reproduce the problem, I'm closing this issue. Please reopen if you have more information.

**Closed by tjgq** 2018-07-11 00:15 UTC

**Comment by goatmessi10** [comment] 2020-06-22 16:15
hey ! Can you tell me how to free up the memory used by the Canvas ?

**Comment by ismaildkc** [comment] 2021-11-04 12:46
I cant import DeviceOrientationControlMethod.js in Vue.js
it returns "Marzipano is not defined" in this file

Im importing like this,

import Marzipano from '../plugins/marzipano/marzipano';
import DeviceOrientation from "../plugins/marzipano/js/DeviceOrientationControlMethod.js";
