### ISSUE TITLE
Generating Tiles

### ISSUE THREAD

**Issue by flyer299** [google/marzipano#71] opened 2017-03-08 16:33 UTC
Are there any recommended best practices for generating tiled images that work with Marzipano?

The web tool will generate the tiles, but I would like to be able to run that process in our own automation system and not tie ourselves to the Marzipano web tool.

**Comment by valeriodeluca** [comment] 2017-03-14 16:23
I try with ptgui, keep in touch

**Comment by flyer299** [comment] 2017-03-14 16:25
So far, KR Pano seems to be the direction we will go with generating tiles.  They have a command line tool that we will be able to automate.   

Wish there was an easier framework to use.

**Comment by valeriodeluca** [comment] 2017-03-14 16:27
ok tks!

**Comment by valeriodeluca** [comment] 2017-03-14 20:44
And multiresolution on Marzipano? It's possible? Sometimes starting Marzipano isn t fast. I d like this speed:

https://pannellum.org/documentation/examples/multiresolution/

by Pannellum, but I very like Marzipano template!

Tks best

**Comment by flyer299** [comment] 2017-03-15 00:44
Marzipano does support Multiresolution tile images.   We have generated multi resolution tile images using KR Pano and displayed them with Marzi.    We are in the process of writting our own automation to automatically generate the tiles from KR Pano.   Our research shows us that it should work just fine, but we haven't completed yet to know for sure.  
[https://github.com/google/marzipano/tree/master/demos/cube-multi-res](url)
[http://www.marzipano.net/demos.html](url)

**Comment by valeriodeluca** [comment] 2017-03-15 16:11
Hi Ken, ok I did tiles with MAKE PANO (MULTIRES) droplet.bat
For a manual use (not automatically) now all I need is it change Marzi tiles folder with New Krpano tiles folder?
Tks man

**Comment by valeriodeluca** [comment] 2017-03-15 18:31
I changed this:

var geometry = new Marzipano.CubeGeometry(sceneData.levels);

with this:

var geometry = new Marzipano.CubeGeometry([
	  { tileSize: 256, size: 256, fallbackOnly: true },
	  { tileSize: 512, size: 512 },
	  { tileSize: 512, size: 1024 },
	  { tileSize: 512, size: 2048 },
	  { tileSize: 512, size: 4096 },
	  { tileSize: 512, size: 8192 },
	  { tileSize: 512, size: 16384 },
	  { tileSize: 512, size: 32768 },
	  { tileSize: 512, size: 65536 }
	]);

but the speed at the start seems the same, tks

**Comment by flyer299** [comment] 2017-03-15 22:24
We are at least a week away from knowing the results of our usage of it.   We are working on some other items first before we circle back to dealing with the Tiles.

**Comment by valeriodeluca** [comment] 2017-03-16 08:41
Ok great! Can I help you on coding or testing or donation? Best

Il 15 mar 2017 11:24 PM, "Ken VeArd" <notifications@github.com> ha scritto:

**Comment by valeriodeluca** [comment] 2017-04-04 12:35
Hi Ken, how are you?
I write to ask you some news about your dev on tiles for marzipano get from
krpano. If I can help you ask me of corse.
Thanks, best
Valerio
deluca.valerio@gmail.com


Il 16 mar 2017 9:41 AM, "Valerio De Luca" <deluca.valerio@gmail.com> ha
scritto:

**Comment by jmprovencher** [comment] 2017-04-14 17:44
Any ideas how it would be possible to implement the Marzipano tool for generating tiles in a Web application or with an official API. It seems like a lot of people would like to implement marzipano in their own application without having to create the tiles with Marzipano tool.

**Comment by valeriodeluca** [comment] 2017-04-14 18:42
Yes it's true..

**Comment by GeorgeRT** [comment] 2017-05-01 18:12
There is a demo for a flat pano. Does this mean marzi supports (panellum does not) partial (cylindrical) panos with tiles generated by krpano?  Thanks.

George

**Comment by valeriodeluca** [comment] 2017-05-01 18:48
I think you can find among demo page on Marzipano website, let know how it goes

**Comment by jmprovencher** [comment] 2017-05-02 15:32
Simply use kr pano DROPLET MAKE PANO (multires) and take the folder created and change the url in the flat multires demo on marzipano demos page

**Comment by GeorgeRT** [comment] 2017-05-02 15:44
Thanks Jean. I'm playing with this right now (but am frequently interrupted, haha).  I guess I have to play with the geometry & limiter with data from the krpano xml as well.

**Comment by jmprovencher** [comment] 2017-05-03 14:19
Yeah if you want to make your process automatic for any panorama generated with KR Pano, create a JSON object based on the krpano XML to generate your geometry.

**Comment by valeriodeluca** [comment] 2017-05-07 18:55
in iframe use or browser use can I get an address to point to selected scene I want of my virtual tour?

For example my virtual tour start with Scene-1 but I want to be free to embed the virtual tour starting with Scene-3.

Or in browser use go directly to Scene-3.

Thanks eb
Best
Valerio

**Comment by Ankit-Solanki** [comment] 2017-09-13 10:49
anyone suggest a code of generating tiles for marzipano.

**Comment by valeriodeluca** [comment] 2017-09-13 11:49
Hi ankit, I m looking for but I don't, someone say to use krpano, keep in
touch for news about

Il 13 set 2017 12:49 PM, "Ankit-Solanki" <notifications@github.com> ha
scritto:

**Comment by martinvirtel** [comment] 2017-10-19 08:43
Here's my krpanotools config file to produce three levels of multi-resolution tiles for marzipano using krpanotools command line utility:

https://gist.github.com/martinvirtel/ebd2433494965b4f37b67eb83cd46654

**Comment by tjgq** [comment] 2017-11-04 04:57
Closing since it's not a bug. You are welcome to continue the discussion in our forum at https://groups.google.com/forum/#!forum/marzipano.

**Closed by tjgq** 2017-11-04 04:57 UTC

**Comment by ai-tushar** [comment] 2017-11-06 07:05
Hello Everyone, i am also building a php application where i would very much like to use the marzipano. but will need to generate tiles in my own server. did anyone find any way to create tiles for marzipano without using the krpano tools ? like in php ?

**Comment by GialiBoM** [comment] 2020-07-18 10:45
Hi everyone!!
What's new on how to create multi-resolution tiles without using the tool?

**Comment by mkubdev** [comment] 2021-05-11 13:19
Hi!
Any news about the tiles generation ? Do we need to use krpano ?
