### ISSUE TITLE
Feature request: block the rotation degrees of an image

### ISSUE THREAD

**Issue by nickrivers** [google/marzipano#140] opened 2018-01-08 16:50 UTC
Hi!,
Is it possible to block the rotation degrees of an image? That is, instead of moving 360 in all directions, you can move, for example 270 only.

I need to visualize images with zones that have nothing, and I would like to be able to block them. It's possible?

Regards!

**Comment by jordyno** [comment] 2018-01-08 17:21
Hi, please take a look [here](https://github.com/google/marzipano/issues/134)

**Comment by tjgq** [comment] 2018-03-23 20:25
Duplicate of #134.

**Closed by tjgq** 2018-03-23 20:25 UTC
