### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by mrlubos** [google/marzipano#256] opened 2019-07-09 09:15 UTC
Hi,

As the title says, this is the error I see in the console when using Marzipano. I am unable to figure out what exactly causes it, but it happens pretty frequently. I noticed it in the previous version, happens in `0.9.0` as well.

```
Stage.js:646 Uncaught TypeError: Cannot read property 'push' of undefined
    at WebGlStage.push../node_modules/marzipano/src/stages/Stage.js.Stage.createTexture (Stage.js:646)
    at exec (chain.js:79)
    at exec (retry.js:35)
    at exec (chain.js:66)
    at ImageUrl.js:107
    at WorkQueue.push../node_modules/marzipano/src/collections/WorkQueue.js.WorkQueue._finish (WorkQueue.js:106)
    at onced (once.js:24)
    at Image.img.onload (HtmlImage.js:79)
```

**Comment by tjgq** [comment] 2019-07-12 01:36
I can't reproduce this on any of the demos at https://www.marzipano.net/demos.html. Do you have an example that triggers the error?

**Comment by tjgq** [comment] 2019-11-10 20:19
Please reopen with repro instructions.

**Comment by mrlubos** [comment] 2019-11-18 01:26
Hey, I haven't been able to create a sample code so far, but here is a list of the APIs I use.

```
ImageUrlSource
CubeGeometry
RectilinearView
```

The issue appears to be a result of destroying the viewer while it's loading the images. Again, I haven't been able to reproduce this in the sample demo, so I suspect it might be particular to the use of APIs above.

I managed to write a hacky fix which requires editing 2 files.

```
// src/stages/WebGl.js, line 184

WebGlStage.prototype.loadImage = function(url, rect, done) {
  if (!this._loader) { // <-- new condition
    return () => {};
  }
  return this._loader.loadImage(url, rect, done);
};
```

and 

```
// src/stages/Stage.js, line 646

if (!this._createTextureWorkQueue) { // <-- insert before this._createTextureWorkQueue.push()
  return done('foo', tile, asset);
}
```

### More context:

The reason `this._createTextureWorkQueue` might be undefined in `Stage.js` is that `Stage.prototype.destroy()` would get called which in turn calls `clearOwnProperties(this)` to clear all properties. A proper fix would ideally ensure `Stage.prototype.createTexture()` never gets called in such case.

The reason we need to patch `WebGlStage.prototype.loadImage()` with `noop()` is the same I guess, our `this._loader` would get removed on `destroy()`. This method is called from `src/sources/ImageUrl.js` like this.

```
var loadImage = stage.loadImage.bind(stage, url, rect);

var loadFn = function(done) {
  // TODO: Deduplicate load requests for the same URL. Although the browser
  // might be smart enough to avoid duplicate requests, they are still unduly
  // impacted by the concurrency parameter.
  return self._loadPool.push(loadImage, function(err, asset) {
    if (err) {
      if (err instanceof NetworkError) {
        // If a network error occurred, wait before retrying.
        retryMap[url] = now();
        self.emit('networkError', asset, err);
      }
      done(err, tile);
    } else {
      // On a successful fetch, forget the previous timeout.
      delete retryMap[url];
      done(null, tile, asset);
    }
  });
};
```

I didn't dig deeper into how `self._loadPool` works, but I noticed that my images always go through the successful path to `done(null, tile, asset)`. I suspect the proper solution would include a check for unloaded viewer perhaps in the callback of this function, as routing the response to `done(err, tile)` produces yet another batch of errors.

What are your thoughts @tjgq?

**Comment by tjgq** [comment] 2019-11-18 01:38
I think your theory makes sense. We generally don't validate that objects are still around when callbacks are invoked, which is obviously a problem when the objects are destroyed.

Instead of adding null checks inside every callback (which is tedious and error-prone), a better fix would be to cancel any pending operations when the viewer/stage/whatever is destroyed. We have the concept of a "cancelable operation" in the codebase - although I'm not particularly proud of its implementation - so this shouldn't be too hard.

**Comment by mrlubos** [comment] 2019-11-18 01:43
Thanks @tjgq. Do you have any documentation for this implementation? I could try to open a pull request fixing this issue, but I wasn’t sure on what arguments to pass to the cancelable operation (or how to use it properly).

**Comment by tjgq** [comment] 2019-11-18 02:42
I investigated it some more, and I'm no longer sure that the explanation is correct.

The "load image & create texture" operation is managed by a `TextureStoreItem` object. This object has a `TextureStoreItem#destroy` method that cancels the operation. This is in turn called by `TextureStore#destroy`.

If you're using the `Viewer` API, then calling `Viewer#destroy` triggers a sequence of calls that eventually calls `TextureStore#destroy` on every `Layer` that `Viewer` is aware of, which would accomplish the above.

Therefore, one of the following must apply:

1. You're calling `Viewer#destroy` in your code, but there is a bug somewhere along the code path described above.

2. You're calling `Viewer#destroy` in your code, but you created a `Layer` or `TextureStore` that `Viewer` isn't aware of (i.e., through some means other than `Viewer#createScene` or `Scene#createLayer`).

3. You're calling `Stage#destroy` in your code. If you're using `Viewer`, you should call `Viewer#destroy` instead. If you're not using `Viewer` and your code is creating a `Stage` directly, then we can investigate whether `Stage#destroy` is doing the right thing or not.

Which one is it?

**Comment by mrlubos** [comment] 2019-11-18 10:21
@tjgq I think it will be option 2. I did some more digging, and this is the implementation.

```
// for every scene data, do this...
const source = new Marzipano.ImageUrlSource((tile) => {
  const result = {
    url: getSceneTileUrl(scene, tile),
  };
  if (isTilePreview(tile)) {
    result.rect = getTileRect(tile);
  }
  return result;
});
// ^ I don't think this is important apart from giving us the `source` value

// This will be the source of problems I think, we monkey-patch the `loadAsset()` method
const { loadAsset } = source;
source.loadAsset = (...args) => {
  const signedUrl = signedUrls[scene]; // check if we have a signed URL for the scene
  const func = loadAsset.bind(source);

  if (signedUrl && !signedUrl.fetching) { // all is good, load the scene. In my crashing example, this never gets called
    return func.call(source, ...args);
  }

  const request = { args, func }; // wrap the request so it can be queued for later
  if (requests[scene]) { // there is already at least 1 queued request, append this one
    requests[scene].push(request);
  } else { // there are no pending requests, create an array with this one
    requests[scene] = [request];
    if (!signedUrl || !signedUrl.fetching) { // we are not fetching signed URLs yet, do it now. This runs once per scene
      fetchSignedUrl(scene);
    }
  }

  // Actual comment from the implementation below, I wonder if this is not the root of the problem
  // Must return a function to avoid breaking Marzipano's chaining.
  return () => {};
};
```

Once we fetch the signed URLs, the pending requests are retried. I keep the original `args` and result of `func` which should be the cancel function, right?

`const cancel = func(...args);`

When the images load after we destroy the viewer, that's when the bug occurs. I tried to place as many checks and conditions inside the wrapper implementation, but nothing helps.

Additionally, I tried doing this after destroying the viewer.

```
const done = args[args.length - 1];
cancel('foo');
done('foo');
```

Both methods return undefined and run without issues, but won't prevent the error from throwing. Do you think you can spot an issue here?

**Comment by tjgq** [comment] 2019-11-19 02:25
I think you're monkey patching correctly, but unless your `loadAsset` function is fully synchronous (which it won't be, if it's loading things from the network), its returned `cancel` must arrange for any asynchronous operations to be canceled.

Let's say `fetchSignedUrl` does something like create an `img` element and set its `onload` callback. The `TextureStore` calls `loadAsset`, which calls `fetchSignedUrl`. At this point, `loadAsset` is done executing, but the `onload` callback is still pending (the `img` hasn't loaded yet). Calling `cancel` as written won't prevent the callback from being called when the image eventually loads.

Most likely, your `fetchSignedUrl` must be written in this way:

```
function fetchSignedUrl() {
  var canceled = false;

  doSomethingAsync((done) => {
    if (canceled) {
       // abort; note that `cancel` still has the responsibility of calling the callback
      return done(new Error('aborted'));
    }
    // continue normally
  });

  return () => {
    // arrange for the callback to abort
    canceled = true;
  };
}
```

Then your monkey-patched `loadAsset` should `return fetchSignedUrl(...)` (i.e., return the `cancel` function).

What I described above is sufficient if `fetchSignedUrl` doesn't chain asynchronous operations (i.e., a callback calls something that receives a second callback). If it does, you can use the `chain` utility method to compose cancelable functions that execute in series, each receiving the result of the former, and aborting the entire chain at the first error. You can see a usage example at the end of the `ImageUrlSource.prototype.loadAsset` implementation.

It's somewhat unfortunate that this machinery exists. Marzipano predates ES6 and the widespread availability of (native) promises and async/await, so we had to make do with callbacks. But note that even with promises or async/await, JavaScript lacks a general-purpose mechanism to express the cancellation of an asychronous operation;  [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) comes close, but it's not fully general.

**Comment by mrlubos** [comment] 2019-11-22 14:17
Thanks for your help @tjgq! I updated our patch with the suggestion above. One small addition I made is to store all cancel callbacks and manually call them on unmount. This seems to have reduced the amount of errors I get, it's actually very hard to reproduce now. I will deploy this fix into production and see what's the success rate. Hopefully I won't be bugging you anymore. Thanks again!

**Comment by tjgq** [comment] 2019-11-24 06:25
You're welcome!

Since Marzipano doesn't seem to be at fault here, I'm going to close this issue. Please reopen if you're still seeing issues that cannot be explained by the above.

**Closed by tjgq** 2019-11-24 06:25 UTC
Labels: bug
