### ISSUE TITLE
View delimiter logic in differenz screen sizes

### ISSUE THREAD

**Issue by thomas-rothe** [google/marzipano#145] opened 2018-01-26 11:56 UTC
Hey to all, 

after a long time of reading manuals, issues, stackoverflow and other sites i built a custom limiter for my rectangular marzipano. My marzipano is not filling out the whole scene, thats why i have to limit the view.

This is the part of my data.js:
`// pitch is vertical moving

      "pitchMin": -0.1,
      "pitchMax": 0.1,
      // yaw is horizontally
      "yawMin": -0.55,
      "yawMax": 0.55,
      // vfov is zooming
      "vfovMin": 0.7, 
      "vfovMax": 0.7,`

This is the part of my index.js:
`limiter = Marzipano.util.compose(
            Marzipano.RectilinearView.limit.pitch(data.pitchMin, data.pitchMax),
            Marzipano.RectilinearView.limit.yaw(data.yawMin, data.yawMax),
            Marzipano.RectilinearView.limit.vfov(data.vfovMin, data.vfovMax)
        );`

This is working fantastic on for example desktop monitor with 1920 x 1080.
On a tablet landscape view the scene is not completly visible.
Changing the orientation to portrait the visible marzipano is more cut off.

**Now the problem is:**
Should i set my parameters for every display resolution?
Is there a mathematically solution to calculate the parameters ?
Or is there a other solution to configure the limiter to diffent display solutions ?

Thanks
Best
Thomas

**Comment by 12557** [comment] 2018-01-26 15:03
Hey thomas, same problem here! Hopefully somebody knows how to make this responsive.

Cheers Matthias

**Comment by thomas-rothe** [comment] 2018-01-26 15:54
![image](https://user-images.githubusercontent.com/5196523/35447998-63a0f6fa-02b9-11e8-9e07-7e388b85ce91.png)

this was cruel in school.
But i do not know :(

**Comment by jordyno** [comment] 2018-01-26 22:48
It's impossible to accomplish this via static pitch/yaw min/max values, as they should change with the FOV. The critical point is to figure out a function for this that would translate these values correctly each time FOV is changed, also taking into account current view range.
What should be emphasized in this issue is that the `pitchMin`, `pitchMax`, `yawMin`, `yawMax ` are just center points of the screen that is allowed to be shown. So the actual amount of panorama content will always differ by the FOV and screen proportions.
Maybe if we could calculate something like screenPitchTop and screenPitchBottom (which would represent pitch values of current screen view of first and last vertical pixel) to compare the the required limited pitch against, that could be the way. But right now I don't know how to achieve this.
Maybe @manuelcabral or @tjgq have an idea we could work on?

**Comment by tjgq** [comment] 2018-03-23 20:25
Duplicate of #134.

**Closed by tjgq** 2018-03-23 20:25 UTC
