### ISSUE TITLE
Adding transitions

### ISSUE THREAD

**Issue by Darq2016** [google/marzipano#25] opened 2016-08-03 00:11 UTC
Hi! I am a graphic designer, not a programmer. I like the Marzipano viewer a lot, the Marzipano tool is easy and straightforward, but I cant find any tutorial to guide me in other issues, like applying the transitions shown as demos in the site. I have downloaded all the code, buy its too hard for me. Any help please?

**Comment by manuelcabral** [comment] 2016-09-15 18:30
Closing as this was discussed on the mailing list and is not a bug.

**Closed by manuelcabral** 2016-09-15 18:30 UTC
