### ISSUE TITLE
WebVR demo doesn't work in Chrome browser of android phone.

### ISSUE THREAD

**Issue by alitashr** [google/marzipano#172] opened 2018-06-19 05:04 UTC
Tried WebVR demo in chrome browser of my android mobile(Samsung S4). It used to work fine few months ago but now it loads the VR but runs too fast as if it's too sensitive of motion. However, it runs well in Samsung Internet browser. 
Version of chrome browser: 67.0.3396.87

**Comment by vectorjedi** [comment] 2018-07-09 14:02
This is due to the fact that the implemented version of the webvr polyfill is broken due to some changes in chrome >m65. The implemented version of the webvr polyfill (supposely v0.9.40) is a few releases behind the current version (v0.10.3) and meanwhile the issue has been patched in the webvr polyfill. The webvr polyfill integration needs to be updated, but may be difficult, since there was a complete refactoring involved. You can read more about it here: https://github.com/immersive-web/webvr-polyfill/releases/tag/v0.10.3

**Comment by tjgq** [comment] 2018-07-15 21:58
Duplicate of #103.

**Closed by tjgq** 2018-07-15 21:58 UTC
