### ISSUE TITLE
WebVR issue in Android based mobile

### ISSUE THREAD

**Issue by MrPrabal** [google/marzipano#159] opened 2018-04-06 08:25 UTC
Recently, WebVR has stopped working in Chrome browser of any android mobile. Earlier being in VR mode, if I move left or right then the VR room would do the same. But one fine day, it all stopped.

What I found out that, in the default Samsung Internet browser, WebVR is working fine as VR was designed, but not in Chrome browser of android mobile. Probably I think that the new update of Chrome browser caused the problem. Could you please investigate the issue.

The version of Chrome browser installed in my mobile is 65.0.3325.109

**Comment by vectorjedi** [comment] 2018-04-06 09:12
That is due to changes Google made to the DeviceMotion and DeviceOrientation Event in Chrome and the Android Vr Services. They reenabled the DeviceOrientation (it ran twice as fast as the requestAnimationFrame cycle, afaik), but in the old WebVr-Polyfill that Marzipano uses it wont work anymore.
The WebVR polyfill needs to be updated to the fixed here.

**Comment by tjgq** [comment] 2018-06-13 22:01
Duplicate of #103.

**Closed by tjgq** 2018-06-13 22:01 UTC
